version: '3.8'

services:
  nuvem:
    build: .
    container_name: nuvem
    networks:
      - rede_recarga
    ports:
      - "5000:5000"
    environment:
      - NUM_PONTOS=5  # Altere este valor para o número desejado de pontos
    command: ["python", "/app/nuvem.py"]

  ponto:
    build: .
    networks:
      - rede_recarga
    environment:
      - BASE_PORT=6000
    command: ["python", "/app/ponto_recarga.py"]
    deploy:
      replicas: 5  # Deve ser igual a NUM_PONTOS

  cliente:
    build: .
    depends_on:
      - nuvem
    networks:
      - rede_recarga
    environment:
      - NUM_CLIENTES=3  # Altere este valor para o número desejado de clientes
    command: ["python", "/app/cliente.py"]
    deploy:
      replicas: 3  # Deve ser igual a NUM_CLIENTES

networks:
  rede_recarga:
    driver: bridge