services:
  nuvem:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nuvem
    volumes:
      - .:/app  # Monta o diretório atual no /app do container
    networks:
      - rede_recarga
    ports:
      - "5000:5000"
    command: ["python", "./nuvem.py"]  # Caminho relativo

  ponto:
    build: .
    volumes:
      - .:/app
    networks:
      - rede_recarga
    command: ["python", "./ponto_recarga.py"]
    deploy:
      replicas: 8 

  cliente:
    build: .
    volumes:
      - .:/app
    depends_on:
      - nuvem
    networks:
      - rede_recarga
    command: ["python", "./cliente.py"]
    deploy:
      replicas: 3

networks:
  rede_recarga:
    driver: bridge