networks:
  rede_recarga:
    driver: bridge
services:
  cliente_1:
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - python
    - ./cliente.py
    depends_on:
    - nuvem
    environment:
    - DOCKER_ENV=true
    - HOSTNAME=cliente_1
    networks:
    - rede_recarga
    volumes:
    - .:/app
  nuvem:
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - python
    - ./nuvem.py
    container_name: nuvem
    environment:
    - DOCKER_ENV=true
    - NUM_PONTOS=1
    networks:
    - rede_recarga
    ports:
    - 5000:5000
    volumes:
    - .:/app
  ponto_1:
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - python
    - ./ponto_recarga.py
    environment:
    - DOCKER_ENV=true
    - PORT=6001
    - PONTO_ID=1
    networks:
    - rede_recarga
    volumes:
    - .:/app
version: '3.8'
